version: '2.1'
services:
  
#Mysql database  
  
  mysql-database:
    image: mysql:5.5
    container_name: mysql-database
    network_mode: "host"  
    hostname: localhost
    ports: 
      - 3306:3306   
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_d
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - /opt/data:/var/lib/mysql
    healthcheck:
      test: exit 0
        
#Mongo database        
        
  mongo-database:
    image: mongo
    container_name: mongo-database
    network_mode: "host"
    hostname: localhost
    ports:
      - 27017:27017
    volumes:
      - /usr/src/home:/data/db
    healthcheck:
      test: exit 0
        
#Neo4j database        

  neo4j-database:
    image: neo4j
    container_name: neo4j-database
    network_mode: "host"
    hostname: localhost
    ports:
      - 7474:7474
      - 7687:7687
    environment: 
      - NEO4J_AUTH=neo4j/godeliver@12
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - $HOME/neo4j/data:/data
    healthcheck:
      test: "exit 0"
